import { PropertyProps } from "@/interfaces";
export const API_URLS = {
  GET_PROPERTIES: "/api/properties",
  BOOK_PROPERTY: "/api/book",
};

export const UI_TEXT = {
  bookNow: "Book Now",
  viewDetails: "View Details",
  confirmStay: "Confirm Stay",
  priceSummary: "Review Order Details",
};

export const PROPERTYLISTINGSAMPLE: PropertyProps[] = [
  {
    name: "Villa Ocean Breeze",
    address: {
      state: "Seminyak",
      city: "Bali",
      country: "Indonesia",
    },
    rating: 4.89,
    category: ["Luxury Villa", "Pool", "Free Parking"],
    price: 3200,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "4-6",
    },
    image: [
      "/assets/Detail Images/image 19.svg",
      "/assets/Detail Images/image 21.svg",
      "/assets/Detail Images/image 22.svg",
      "/assets/Detail Images/image 24.svg",
    ],
    discount: "",
    iconsUrl: [
      "/assets/Icons/bed 1.svg",
      "/assets/Icons/bathtub 1.svg",
      "/assets/Icons/people 1.svg",
    ],
    description: [
      "Feel like exploring the Dominican? Start the day with a hike on one of Playa Moron’s many trails. Weave your way around the gated community to find secluded sandy coves for swimming and paddleboarding. When you’Feel like exploring the Dominican? Start the day with a hike on one of Playa Moron’s many trails. Weave your way around the gated community to find secluded sandy coves for swimming and paddleboarding. When you’re ready to chill with friends, the beach house pool awaits. Spend the night entertaining in the outdoor lounge, sipping drinks in the hot tub, and gazing out over incredible ocean views.",
      "The Space",
      "BEDROOM & BATHROOM",
      "• Bedroom 1 - Primary: King size bed, Ensuite bathroom with stand-alone rain shower, Dual vanity, Walk-in closet, Television, Sofa, Deck, Balcony, Ocean view",
      "Perfect for families or groups seeking a premium getaway at $3200/night.",
    ],
  },
  {
    name: "Mountain Escape Chalet",
    address: {
      state: "Aspen",
      city: "Colorado",
      country: "USA",
    },
    rating: 4.7,
    category: ["Mountain View", "Fireplace", "Self Checkin"],
    price: 1800,
    offers: {
      bed: "4",
      shower: "2",
      occupants: "5-7",
    },
    image: "https://example.com/image2.jpg",
    discount: "30",
    description: [
      "Enjoy breathtaking mountain views in Aspen, Colorado. This cozy chalet offers a fireplace, self check-in, and a 4.7-star guest rating.",
      "Ideal for ski trips or relaxing retreats at $1800/night.",
    ],
  },
  {
    name: "Cozy Desert Retreat",
    address: {
      state: "Palm Springs",
      city: "California",
      country: "USA",
    },
    rating: 4.92,
    category: ["Desert View", "Pet Friendly", "Self Checkin"],
    price: 1500,
    offers: {
      bed: "2",
      shower: "1",
      occupants: "2-3",
    },
    image: "https://example.com/image3.jpg",
    discount: "",
    description: [
      "A pet-friendly desert retreat in Palm Springs, California, with self check-in and beautiful desert views.",
      "Highly rated at 4.92 stars, perfect for couples or small families at $1500/night.",
    ],
  },
  {
    name: "City Lights Penthouse",
    address: {
      state: "New York",
      city: "New York",
      country: "USA",
    },
    rating: 4.85,
    category: ["City View", "Free WiFi", "24h Checkin"],
    price: 4500,
    offers: {
      bed: "2",
      shower: "2",
      occupants: "2-4",
    },
    image: "https://example.com/image4.jpg",
    discount: "15",
    description: [
      "Experience the vibrant city life in New York with this penthouse offering stunning city views, free WiFi, and 24h check-in.",
      "Rated 4.85 stars, ideal for business or leisure at $4500/night.",
    ],
  },
  {
    name: "Riverside Cabin",
    address: {
      state: "Queenstown",
      city: "Otago",
      country: "New Zealand",
    },
    rating: 4.77,
    category: ["Riverside", "Private Dock", "Free Kayaks"],
    price: 2800,
    offers: {
      bed: "3",
      shower: "2",
      occupants: "4-6",
    },
    image: "https://example.com/image5.jpg",
    discount: "20",
    description: [
      "Relax by the riverside in Otago, New Zealand. This cabin features a private dock, free kayaks, and a 4.77-star rating.",
      "Great for nature lovers at $2800/night.",
    ],
  },
  {
    name: "Modern Beachfront Villa",
    address: {
      state: "Sidemen",
      city: "Bali",
      country: "Indonesia",
    },
    rating: 4.95,
    category: ["Beachfront", "Private Pool", "Chef Service"],
    price: 5000,
    offers: {
      bed: "5",
      shower: "4",
      occupants: "8-10",
    },
    image: "https://example.com/image6.jpg",
    discount: "",
    description: [
      "Enjoy a modern beachfront villa in Bali's Sidemen with a private pool and chef service.",
      "Rated 4.95 stars, perfect for large groups at $5000/night.",
    ],
  },
  {
    name: "Lakeside Chalet",
    address: {
      state: "Banff",
      city: "Alberta",
      country: "Canada",
    },
    rating: 4.65,
    category: ["Lakeside", "Mountain View", "Hiking Trails"],
    price: 2300,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "4-5",
    },
    image: "https://example.com/image7.jpg",
    discount: "10",
    description: [
      "Charming chalet by the lake in Banff, Alberta. Features mountain views, hiking trails, and a 4.65-star rating.",
      "Ideal for outdoor enthusiasts at $2300/night.",
    ],
  },
  {
    name: "Tropical Garden Villa",
    address: {
      state: "Koh Samui",
      city: "Surat Thani",
      country: "Thailand",
    },
    rating: 4.8,
    category: ["Garden", "Free Parking", "Self Checkin"],
    price: 2750,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "5-6",
    },
    image: "https://example.com/image8.jpg",
    discount: "25",
    description: [
      "Relax in a tropical garden villa in Koh Samui, Thailand. Free parking, self check-in, and a 4.8-star rating.",
      "A great choice for families at $2750/night.",
    ],
  },
  {
    name: "Urban Loft",
    address: {
      state: "Berlin",
      city: "Berlin",
      country: "Germany",
    },
    rating: 4.6,
    category: ["City Center", "Free WiFi", "24h Checkin"],
    price: 2000,
    offers: {
      bed: "2",
      shower: "1",
      occupants: "2-3",
    },
    image: "https://example.com/image9.jpg",
    discount: "",
    description: [
      "Modern loft in the heart of Berlin, Germany. Enjoy free WiFi, 24h check-in, and a 4.6-star rating.",
      "Perfect for city explorers at $2000/night.",
    ],
  },
  {
    name: "Secluded Forest Cabin",
    address: {
      state: "Whistler",
      city: "British Columbia",
      country: "Canada",
    },
    rating: 4.72,
    category: ["Secluded", "Hot Tub", "Self Checkin"],
    price: 2600,
    offers: {
      bed: "4",
      shower: "2",
      occupants: "5-7",
    },
    image: "https://example.com/image10.jpg",
    discount: "40",
    description: [
      "Escape to a secluded forest cabin in Whistler, British Columbia. Hot tub, self check-in, and a 4.72-star rating.",
      "Ideal for a peaceful retreat at $2600/night.",
    ],
  },
  {
    name: "Cliffside Villa",
    address: {
      state: "Amalfi",
      city: "Salerno",
      country: "Italy",
    },
    rating: 4.93,
    category: ["Cliffside", "Infinity Pool", "Sea View"],
    price: 6000,
    offers: {
      bed: "4",
      shower: "4",
      occupants: "6-8",
    },
    image: "https://example.com/image11.jpg",
    discount: "50",
    description: [
      "Spectacular cliffside villa in Amalfi, Italy, with an infinity pool and sea views.",
      "Rated 4.93 stars, perfect for luxury seekers at $6000/night.",
    ],
  },
  {
    name: "Coastal Escape Villa",
    address: {
      state: "Noosa",
      city: "Queensland",
      country: "Australia",
    },
    rating: 4.83,
    category: ["Beachfront", "Pet Friendly", "Free Parking"],
    price: 3400,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "4-6",
    },
    image: "https://example.com/image12.jpg",
    discount: "",
    description: [
      "Coastal villa in Queensland, Australia, with beachfront access, pet-friendly amenities, and free parking.",
      "Rated 4.83 stars, great for families at $3400/night.",
    ],
  },
  {
    name: "Historical Villa",
    address: {
      state: "Florence",
      city: "Tuscany",
      country: "Italy",
    },
    rating: 4.67,
    category: ["Historical", "Free Breakfast", "Self Checkin"],
    price: 2700,
    offers: {
      bed: "2",
      shower: "2",
      occupants: "2-4",
    },
    image: "https://example.com/image13.jpg",
    discount: "35",
    description: [
      "Stay in a historical villa in Tuscany, Italy, with free breakfast and self check-in.",
      "Rated 4.67 stars, perfect for a cultural escape at $2700/night.",
    ],
  },
  {
    name: "Downtown Apartment",
    address: {
      state: "Tokyo",
      city: "Tokyo",
      country: "Japan",
    },
    rating: 4.81,
    category: ["City Center", "Free WiFi", "Public Transport"],
    price: 2200,
    offers: {
      bed: "1",
      shower: "1",
      occupants: "2",
    },
    image: "https://example.com/image14.jpg",
    discount: "",
    description: [
      "Modern downtown apartment in Tokyo, Japan, with free WiFi and easy access to public transport.",
      "Rated 4.81 stars, ideal for city stays at $2200/night.",
    ],
  },
  {
    name: "Luxury Safari Lodge",
    address: {
      state: "Serengeti",
      city: "Mara",
      country: "Tanzania",
    },
    rating: 4.97,
    category: ["Safari", "Guided Tours", "Free Breakfast"],
    price: 4500,
    offers: {
      bed: "4",
      shower: "4",
      occupants: "6-8",
    },
    image: "https://example.com/image15.jpg",
    discount: "20",
    description: [
      "Experience a luxury safari lodge in Mara, Tanzania, with guided tours and free breakfast.",
      "Rated 4.97 stars, perfect for adventure seekers at $4500/night.",
    ],
  },
  {
    name: "Countryside Cottage",
    address: {
      state: "Cotswolds",
      city: "Gloucestershire",
      country: "UK",
    },
    rating: 4.58,
    category: ["Countryside", "Fireplace", "Self Checkin"],
    price: 1800,
    offers: {
      bed: "2",
      shower: "1",
      occupants: "2-4",
    },
    image: "https://example.com/image16.jpg",
    discount: "25",
    description: [
      "Charming countryside cottage in Gloucestershire, UK, with a fireplace and self check-in.",
      "Rated 4.58 stars, great for a peaceful escape at $1800/night.",
    ],
  },
  {
    name: "Riverfront Mansion",
    address: {
      state: "Paris",
      city: "Île-de-France",
      country: "France",
    },
    rating: 4.86,
    category: ["Riverfront", "Private Garden", "Self Checkin"],
    price: 5000,
    offers: {
      bed: "4",
      shower: "3",
      occupants: "6-8",
    },
    image: "https://example.com/image17.jpg",
    discount: "30",
    description: [
      "Elegant riverfront mansion in Île-de-France, Paris, with a private garden and self check-in.",
      "Rated 4.86 stars, ideal for luxury stays at $5000/night.",
    ],
  },
  {
    name: "Ski Chalet",
    address: {
      state: "Zermatt",
      city: "Valais",
      country: "Switzerland",
    },
    rating: 4.75,
    category: ["Mountain View", "Ski Access", "Fireplace"],
    price: 3900,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "4-5",
    },
    image: "https://example.com/image18.jpg",
    discount: "",
    description: [
      "Ski chalet in Zermatt, Switzerland, with mountain views, ski access, and a cozy fireplace.",
      "Rated 4.75 stars, perfect for winter getaways at $3900/night.",
    ],
  },
  {
    name: "Island Paradise Villa",
    address: {
      state: "Mahe",
      city: "Victoria",
      country: "Seychelles",
    },
    rating: 4.98,
    category: ["Beachfront", "Private Pool", "Chef Service"],
    price: 6500,
    offers: {
      bed: "5",
      shower: "5",
      occupants: "8-10",
    },
    image: "https://example.com/image19.jpg",
    discount: "60",
    description: [
      "Stunning island paradise villa in Victoria, Seychelles, with a private pool and chef service.",
      "Rated 4.98 stars, the ultimate luxury at $6500/night.",
    ],
  },
  {
    name: "Clifftop Retreat",
    address: {
      state: "Cape Town",
      city: "Western Cape",
      country: "South Africa",
    },
    rating: 4.78,
    category: ["Ocean View", "Private Pool", "Self Checkin"],
    price: 4100,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "4-5",
    },
    image: "https://example.com/image20.jpg",
    discount: "",
    description: [
      "Clifftop retreat in Western Cape, South Africa, with ocean views, private pool, and self check-in.",
      "Rated 4.78 stars, perfect for relaxing escapes at $4100/night.",
    ],
  },
];
